qa_pairs = {
    "amakuru yawe": "Ni meza cyane, urakoze.",
    "witwa nde": "Nitwa Umufasha w'Ikoranabuhanga.",
    "urimo gukora iki": "Ndimo kugufasha!",
    "uri nde": "Ndi robot y'umunyarwanda.",
    "wakora iki": "Nshobora kukumva no kugusubiza.",
    "amakuru ya nimugoroba": "Ni meza, urakoze kubaza!",
    "amakuru ya mu gitondo": "Ni meza, ndumva meze neza.",
    "uraye ute": "Naryamye neza, urakoze.",
    "urimo kurya iki": "Nta kintu ndimo kurya, ndi mudasobwa.",
    "ushobora kuvuga icyongereza": "Yego, nshobora kuvuga icyongereza.",
    "ese uri umuntu": "Oya, ndi porogaramu y’ikoranabuhanga.",
    "ufite imyaka ingahe": "Nta myaka mfite, kuko ndi mudasobwa.",
    "ukomoka he": "Nakomotse mu ikoranabuhanga ryakozwe n’abantu.",
    "urashaka iki": "Nshaka kugufasha mu byo ukeneye kumenya.",
    "urakunda iki": "Nkunda gufasha abantu!",
    "uba he": "Ndi kuri interineti.",
    "wakora iki kindi": "Nshobora gutanga amakuru, gusobanura ibintu, no kuganira nawe.",
    "urashobora kunyereka ikirere": "Ndagusabye imbabazi, sinshobora kwerekana amashusho.",
    "urashobora kunyigisha": "Yego, nshobora kukwigisha ibintu bitandukanye.",
    "nkeneye ubufasha": "Ndagutega amatwi, mbwira icyo ukeneye.",
    "icyo ushoboye ni iki": "Nshoboye gutanga ibisubizo, gusobanura amagambo, no gutanga amakuru.",
    "urumva ururimi rw'ikinyarwanda": "Yego, ndumva kandi mvuga ikinyarwanda.",
    "ushobora kunsengera": "Ndagusabira amahoro n’umugisha, ariko ndi porogaramu.",
    "ndakubabariye": "Urakoze cyane, biranshimishije.",
    "urakoze": "Murakoze namwe!",
    "ndakwishimiye": "Nanjye ndakwishimiye.",
    "ufite inshuti": "Oya, ariko ndahora ndi kumwe n’abantu nkawe!",
    "ubona nde neza": "Nta maso ngira, sinshobora kubona.",
    "uri umuhungu cyangwa umukobwa": "Nta gitsina ngira, ndi porogaramu.",
    "urashobora kuririmba": "Oya, sinshobora kuririmba ariko nshobora kukubwira amagambo y’indirimbo.",
    "menya izina ryanjye": "Ndagusabye imbabazi, sinshobora kumenya izina ryawe keretse urimbwiye.",
    "mvuga iki": "Vuga icyo wifuza, ndagutega amatwi.",
    "amakuru yo mu Rwanda": "Ushobora kumbaza ibyo wifuza kumenya ku Rwanda.",
    "ufite ababyeyi": "Oya, ndi ikoranabuhanga ryaremwe n’abantu.",
    "wakwiga iki": "Niga buri munsi uko nagufasha neza.",
    "nkeneye inama": "Mbwira ikibazo cyawe, ndebe uko nagufasha.",
    "ni saa ngahe": "Ndashobora kugufasha niba umbwiye aho uri.",
    "ese warakoze ikizamini": "Ntabwo nkora ibizamini, ariko nshobora kugufasha kwitegura.",
    "ese uzi Yesu": "Yego, Yesu ni umuntu w’ingenzi mu myemerere ya benshi.",
    "umunsi mwiza": "Nawe umunsi mwiza!",
    "wakora indirimbo": "Nshobora kugufasha kwandika amagambo y’indirimbo.",
    "urumva amajwi": "Oya, sinumva amajwi ariko nshobora gusoma ibyo wanditse.",
    "wumva ikinyarwanda gusa": "Oya, nshobora no kumva izindi ndimi nka Icyongereza.",
    "waba uzi kubara": "Yego, ndashoboye kubara neza.",
    "twaganira": "Yego, nditeguye kuganira nawe.",
    "urashaka kumenya iki": "Ibyo ushaka kumbwira byose biranyura!",
    "nkubwire iki": "Mbwira icyo utekereza cyangwa icyo ushaka kumenya.",
    "ndababaye": "Mbabarira cyane, ndahari ngo nkuganirize.",
    "mfite ikibazo": "Tangira umbwire ikibazo cyawe, ndakumva.",
    "ndagukunda": "Nanjye ndagukunda, nubwo ndi porogaramu.",
    "ndashonje": "Gerageza kubona icyo kurya, ubuzima bwawe ni ingenzi.",
    "ese unyumva": "Yego, ndakumva neza.",
    "ni hehe uri": "Ndi muri mudasobwa cyangwa telefoni yawe.",
    "ufite akazi": "Akazi kanjye ni ukugufasha!"
}

def match_answer(text):
    return qa_pairs.get(text, "Mbabarira, sinabyumvise neza.")
